/-
Copyright 2026 The Formal Conjectures Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/
module

public import FormalConjecturesTest.Period.MeasureTheory.Integral.CurveIntegral.Map
public import Mathlib.Analysis.Calculus.ContDiff.Operations

@[expose] public noncomputable section

/-!
# Periods of a 1-form

For a 1-form $\omega$ on a normed space $E$ and a set $S \subseteq E$, the *periods* of $\omega$
on $S$ are the integrals $\int_\gamma \omega$ over the $C^1$ loops $\gamma$ in $S$
(`curveIntegralPeriods`). The set of periods contains $0$ (constant loops), is stable under
negation (reversed loops) and monotone in $S$, and transforms under an affine bijection
$x \mapsto A x + c$ by pulling back the form (`curveIntegralPeriods_image_add_const`).

For a closed 1-form on an open set the periods form an additive subgroup, generated by the
integrals over a basis of the first homology; this is the situation for the invariant
differential of an elliptic curve over $\mathbb{C}$, whose periods are the period lattice
(`WeierstrassCurve.integralPeriodLattice_eq`). Concatenation of loops is not treated here
because the concatenation of two $C^1$ loops is only piecewise $C^1$.

*References:*
- [LMFDB](https://www.lmfdb.org/knowledge/show/ec.q.period_lattice), knowl
  `ec.q.period_lattice`
-/

open MeasureTheory Set
open scoped unitInterval

variable {𝕜 E E' F : Type*} [RCLike 𝕜] [NormedAddCommGroup E] [NormedSpace 𝕜 E]
  [NormedAddCommGroup E'] [NormedSpace 𝕜 E'] [NormedAddCommGroup F] [NormedSpace 𝕜 F]
  [NormedSpace ℝ E] [NormedSpace ℝ E']

/-- The periods of a 1-form `ω` on a set `S`: the integrals of `ω` along the `C¹` loops in `S`. -/
def curveIntegralPeriods (ω : E → E →L[𝕜] F) (S : Set E) : Set F :=
  {w | ∃ (p : E) (γ : Path p p), ContDiffOn ℝ 1 γ.extend I ∧ range γ ⊆ S ∧ ∫ᶜ x in γ, ω x = w}

variable {ω : E → E →L[𝕜] F} {S T : Set E}

/-- The integral of `ω` along a `C¹` loop with image in `S` is a period of `ω` on `S`. -/
lemma curveIntegral_mem_curveIntegralPeriods {p : E} (γ : Path p p)
    (hγ : ContDiffOn ℝ 1 γ.extend I) (hS : range γ ⊆ S) :
    ∫ᶜ x in γ, ω x ∈ curveIntegralPeriods ω S := ⟨p, γ, hγ, hS, rfl⟩

/-- The periods of `ω` on `S` are periods of `ω` on any larger set. -/
lemma curveIntegralPeriods_mono (h : S ⊆ T) : curveIntegralPeriods ω S ⊆ curveIntegralPeriods ω T :=
  fun _ ⟨p, γ, hγ, hS, hw⟩ ↦ ⟨p, γ, hγ, hS.trans h, hw⟩

/-- Zero is a period of `ω` on any nonempty set. -/
lemma zero_mem_curveIntegralPeriods (hS : S.Nonempty) : 0 ∈ curveIntegralPeriods ω S :=
  hS.imp fun p hp ↦ ⟨.refl p, contDiffOn_const, by simpa using hp, curveIntegral_refl ω p⟩

/-- The periods of `ω` on `S` are stable under negation. -/
lemma neg_mem_curveIntegralPeriods {w : F} (hw : w ∈ curveIntegralPeriods ω S) :
    -w ∈ curveIntegralPeriods ω S := by
  obtain ⟨p, γ, hγ, hS, rfl⟩ := hw
  refine ⟨p, γ.symm, ?_, by rwa [γ.symm_range], curveIntegral_symm ω γ⟩
  rw [Path.extend_symm]
  exact hγ.comp (by fun_prop) fun _ ↦ Set.Icc.mem_iff_one_sub_mem.mp

variable [NormedSpace ℝ F] [IsScalarTower ℝ 𝕜 E] [IsScalarTower ℝ 𝕜 E']

/-- One inclusion of `curveIntegralPeriods_image_add_const`: pushing a loop forward along
`x ↦ A x + c` turns a period of the pullback into a period of `ω`. -/
private lemma curveIntegralPeriods_subset_image_add_const (ω : E' → E' →L[𝕜] F) (A : E ≃L[𝕜] E')
    (c : E') (S : Set E) : curveIntegralPeriods (fun x ↦ (ω (A x + c)).comp (A : E →L[𝕜] E')) S ⊆
      curveIntegralPeriods ω ((fun x ↦ A x + c) '' S) := by
  have hA : ContDiff ℝ 1 fun x : E ↦ A x + c :=
    ((A : E →L[𝕜] E').restrictScalars ℝ).contDiff.add contDiff_const
  rintro w ⟨p, γ, hγ, hS, rfl⟩
  exact ⟨A p + c, γ.map' (f := fun x ↦ A x + c) (by fun_prop), hA.comp_contDiffOn hγ,
    range_subset_iff.2 fun t ↦ ⟨γ t, hS ⟨t, rfl⟩, rfl⟩,
    curveIntegral_map_add_const ω (A : E →L[𝕜] E') c γ (hγ.differentiableOn one_ne_zero)⟩

/-- The periods of `ω` on the image of `S` under an affine bijection `x ↦ A x + c` are the periods
of the pullback `x ↦ (ω (A x + c)).comp A` on `S`. -/
theorem curveIntegralPeriods_image_add_const (ω : E' → E' →L[𝕜] F) (A : E ≃L[𝕜] E') (c : E')
    (S : Set E) : curveIntegralPeriods ω ((fun x ↦ A x + c) '' S) =
      curveIntegralPeriods (fun x ↦ (ω (A x + c)).comp (A : E →L[𝕜] E')) S := by
  refine subset_antisymm ?_ (curveIntegralPeriods_subset_image_add_const ω A c S)
  have key := curveIntegralPeriods_subset_image_add_const
    (fun x ↦ (ω (A x + c)).comp (A : E →L[𝕜] E')) A.symm (-(A.symm c)) ((fun x ↦ A x + c) '' S)
  have hform : (fun y ↦ (((ω (A (A.symm y + -(A.symm c)) + c)).comp (A : E →L[𝕜] E'))).comp
      (A.symm : E' →L[𝕜] E)) = ω := by
    ext y v
    simp
  have himg : (fun y ↦ A.symm y + -(A.symm c)) '' ((fun x ↦ A x + c) '' S) = S := by
    simp [Set.image_image]
  rwa [hform, himg] at key

end
